---
- name: Prepare
  hosts: k3s_cluster
  remote_user: sondn98
  become: yes
  roles:
    - k3s.orchestration.prereq
    - k3s.orchestration.airgap
    - k3s.orchestration.raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - k3s.orchestration.k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - k3s.orchestration.k3s_agent